version: "3.6"

services:
  flagr:
    image: ghcr.io/openflagr/flagr:1.1.13
    ports:
      - "18000:18000"
    environment:
      FLAGR_DB_DBDRIVER: "sqlite3"
      FLAGR_DB_DBCONNECTIONSTR: "/tmp/flagr.sqlite3"
    command: sh -c "sleep 3 && ./flagr"

